"""
This file is automatically generated by xDSL and not meant to be modified.

It was generated from /Users/sueszli/dev/xdsl/xdsl/dialects/cmath.irdl
"""

from xdsl.dialects.builtin import (
    Float32Type,
    Float64Type,
)
from xdsl.ir import (
    Dialect,
    OpResult,
    ParametrizedAttribute,
    TypeAttribute,
)
from xdsl.irdl import (
    IRDLOperation,
    Operand,
)

class complex(TypeAttribute, ParametrizedAttribute):
    elem: Float32Type | Float64Type

class NormOp(IRDLOperation):
    in_: Operand
    out: OpResult

class MulOp(IRDLOperation):
    lhs: Operand
    rhs: Operand
    res: OpResult

Cmath: Dialect
