
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'API'
    label: 'API'
  - title: 'Examples'
    label: 'examples'
  - title: 'Documentation'
    label: 'documentation'
  - title: 'Compiler'
    label: 'compiler'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug-py-minor'
      - 'bug-py'
  - title: 'Benchmarking'
    label: 'benchmarking'
  - title: 'Testing'
    label: 'testing'
  - title: 'Continuous Integration'
    label: 'CI'
  - title: 'Installation'
    labels:
      - 'docker'
      - 'installation'
      - 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
