
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'xDSL framework'
    labels:
      - 'core'
      - 'rewriting'
      - 'frontend'
  - title: 'Dialects'
    label: 'dialects'
  - title: 'API'
    label: 'API'
  - title: 'Examples/Tutorials'
    label: 'examples'
  - title: '🗎 Documentation'
    labels:
      - 'documentation'
      - 'tests'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: 'Testing'
    labels:
      - 'testing'
      - 'tests'
  - title: 'Continuous Integration'
    label: 'CI'
  - title: 'Installation'
    labels:
      - 'installation'
      - 'dependencies'
  - title: 'Miscellaneous'
    labels:
      - 'minor'
      - 'misc'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
