"""
This type stub file was generated by pyright.
"""

def get_library_name():  # -> Literal['libllvmlite.dylib']:
    """
    Return the name of the llvmlite shared library file.
    """
    ...

def get_library_files():  # -> list[str]:
    """
    Return the names of shared library files needed for this platform.
    """
    ...
