class DuplicatedNameError(NameError): ...

class NameScope:
    def __init__(self) -> None: ...
    def is_used(self, name): ...
    def register(self, name, deduplicate=...): ...
    def deduplicate(self, name): ...
    def get_child(self): ...

class _StrCaching: ...

class _StringReferenceCaching:
    def get_reference(self): ...

class _HasMetadata:
    def set_metadata(self, name, node): ...
