"""
This type stub file was generated by pyright.
"""

class Context:
    def __init__(self) -> None: ...
    def get_identified_type(self, name, packed=...):  # -> IdentifiedStructType:
        ...

global_context = ...
