class Module:
    def __init__(self, name=..., context=...) -> None: ...
    def str_ditok_operands(self, operands): ...
    def add_metadata(self, operands): ...
    def add_debug_info(self, kind, operands, is_distinct=...): ...
    def add_named_metadata(self, name, element=...): ...
    def get_named_metadata(self, name): ...
    @property
    def functions(self): ...
    @property
    def global_values(self): ...
    def get_global(self, name): ...
    def add_global(self, globalvalue): ...
    def get_unique_name(self, name=...): ...
    def declare_intrinsic(self, intrinsic, tys=..., fnty=...): ...
    def get_identified_types(self): ...
    def __repr__(self): ...
