class Visitor:
    def visit(self, module): ...
    def visit_Function(self, func): ...
    def visit_BasicBlock(self, bb): ...
    def visit_Instruction(self, instr): ...
    @property
    def module(self): ...
    @property
    def function(self): ...
    @property
    def basic_block(self): ...

class CallVisitor(Visitor):
    def visit_Instruction(self, instr): ...
    def visit_Call(self, instr): ...

class ReplaceCalls(CallVisitor):
    def __init__(self, orig, repl) -> None: ...
    def visit_Call(self, instr): ...

def replace_all_calls(mod, orig, repl): ...
