from typing_extensions import Self

class Type: ...

class PointerType(Type):
    def __init__(self, pointee=..., addrspace=...) -> None: ...

class VoidType(Type): ...

class FunctionType(Type):
    def __init__(self, return_type, args, var_arg=...) -> None: ...

class IntType(Type):
    null = ...
    def __new__(cls, bits) -> Self: ...

class _BaseFloatType(Type): ...
class HalfType(_BaseFloatType): ...
class FloatType(_BaseFloatType): ...
class DoubleType(_BaseFloatType): ...

class VectorType(Type):
    def __init__(self, element, count) -> None: ...

class Aggregate(Type): ...

class ArrayType(Aggregate):
    def __init__(self, element, count) -> None: ...

class BaseStructType(Aggregate): ...

class LiteralStructType(BaseStructType):
    def __init__(self, elems, packed=...) -> None: ...
