// RUN: xdsl-opt %s -p stencil-shape-inference,convert-stencil-to-ll-mlir --print-op-generic | filecheck %s

"builtin.module"() ({
  "func.func"() ({
  ^0(%0 : f64, %1 : !stencil.field<?x?x?xf64>):
    %2 = "stencil.cast"(%1) {"lb" = #stencil.index<-3, -3, -3>, "ub" = #stencil.index<67, 67, 67>} : (!stencil.field<?x?x?xf64>) -> !stencil.field<70x70x70xf64>
    %3 = "stencil.apply"(%0) ({
    ^1(%4 : f64):
      %5 = "arith.constant"() {"value" = 1.0 : f64} : () -> f64
      %6 = "arith.addf"(%4, %5) : (f64, f64) -> f64
      "stencil.return"(%6) : (!stencil.result<f64>) -> ()
    }) : (f64) -> !stencil.temp<?x?x?xf64>
    "stencil.store"(%3, %2) {"lb" = #stencil.index<1, 2, 3>, "ub" = #stencil.index<65, 66, 63>} : (!stencil.temp<?x?x?xf64>, !stencil.field<64x64x60xf64>) -> ()
    "func.return"() : () -> ()
  }) {"function_type" = (f64, !stencil.field<?x?x?xf64>) -> (), "sym_name" = "stencil_float64_arg"} : () -> ()

  "func.func"() ({
  ^2(%7 : f32, %8 : !stencil.field<?x?x?xf32>):
    %9 = "stencil.cast"(%8) {"lb" = #stencil.index<-3, -3, -3>, "ub" = #stencil.index<67, 67, 67>} : (!stencil.field<?x?x?xf32>) -> !stencil.field<70x70x70xf32>
    %10 = "stencil.apply"(%7) ({
    ^3(%11 : f32):
      %12 = "arith.constant"() {"value" = 1.0 : f32} : () -> f32
      %13 = "arith.addf"(%11, %12) : (f32, f32) -> f32
      "stencil.return"(%13) : (f32) -> ()
    }) : (f32) -> !stencil.temp<?x?x?xf32>
    "stencil.store"(%10, %9) {"lb" = #stencil.index<1, 2, 3>, "ub" = #stencil.index<65, 66, 63>} : (!stencil.temp<?x?x?xf32>, !stencil.field<70x70x70xf32>) -> ()
    "func.return"() : () -> ()
  }) {"function_type" = (f32, !stencil.field<?x?x?xf32>) -> (), "sym_name" = "stencil_float32_arg"} : () -> ()
}) : () -> ()

// CHECK:      "builtin.module"() ({
// CHECK-NEXT:   "func.func"() ({
// CHECK-NEXT:   ^0(%0 : f64, %1 : memref<?x?x?xf64>):
// CHECK-NEXT:     %2 = "memref.cast"(%1) : (memref<?x?x?xf64>) -> memref<70x70x70xf64>
// CHECK-NEXT:     %3 = "memref.subview"(%2) {"static_offsets" = array<i64: 4, 5, 6>, "static_sizes" = array<i64: 64, 64, 60>, "static_strides" = array<i64: 1, 1, 1>, "operand_segment_sizes" = array<i32: 1, 0, 0, 0>} : (memref<70x70x70xf64>) -> memref<64x64x60xf64, strided<[4900, 70, 1], offset: 19956>>
// CHECK-NEXT:     %4 = "arith.constant"() {"value" = 0 : index} : () -> index
// CHECK-NEXT:     %5 = "arith.constant"() {"value" = 1 : index} : () -> index
// CHECK-NEXT:     %6 = "arith.constant"() {"value" = 64 : index} : () -> index
// CHECK-NEXT:     %7 = "arith.constant"() {"value" = 64 : index} : () -> index
// CHECK-NEXT:     %8 = "arith.constant"() {"value" = 60 : index} : () -> index
// CHECK-NEXT:     "scf.parallel"(%4, %6, %5) ({
// CHECK-NEXT:     ^1(%9 : index):
// CHECK-NEXT:       "scf.for"(%4, %7, %5) ({
// CHECK-NEXT:       ^2(%10 : index):
// CHECK-NEXT:         "scf.for"(%4, %8, %5) ({
// CHECK-NEXT:         ^3(%11 : index):
// CHECK-NEXT:           %12 = "arith.constant"() {"value" = 1.0 : f64} : () -> f64
// CHECK-NEXT:           %13 = "arith.addf"(%0, %12) : (f64, f64) -> f64
// CHECK-NEXT:           "memref.store"(%13, %3, %9, %10, %11) : (f64, memref<64x64x60xf64, strided<[4900, 70, 1], offset: 19956>>, index, index, index) -> ()
// CHECK-NEXT:           "scf.yield"() : () -> ()
// CHECK-NEXT:         }) : (index, index, index) -> ()
// CHECK-NEXT:         "scf.yield"() : () -> ()
// CHECK-NEXT:       }) : (index, index, index) -> ()
// CHECK-NEXT:       "scf.yield"() : () -> ()
// CHECK-NEXT:     }) {"operand_segment_sizes" = array<i32: 1, 1, 1, 0>} : (index, index, index) -> ()
// CHECK-NEXT:     "func.return"() : () -> ()
// CHECK-NEXT:   }) {"function_type" = (f64, memref<?x?x?xf64>) -> (), "sym_name" = "stencil_float64_arg"} : () -> ()
// CHECK-NEXT:   "func.func"() ({
// CHECK-NEXT:   ^4(%14 : f32, %15 : memref<?x?x?xf32>):
// CHECK-NEXT:     %16 = "memref.cast"(%15) : (memref<?x?x?xf32>) -> memref<70x70x70xf32>
// CHECK-NEXT:     %17 = "memref.subview"(%16) {"static_offsets" = array<i64: 4, 5, 6>, "static_sizes" = array<i64: 64, 64, 60>, "static_strides" = array<i64: 1, 1, 1>, "operand_segment_sizes" = array<i32: 1, 0, 0, 0>} : (memref<70x70x70xf32>) -> memref<64x64x60xf32, strided<[4900, 70, 1], offset: 19956>>
// CHECK-NEXT:     %18 = "arith.constant"() {"value" = 0 : index} : () -> index
// CHECK-NEXT:     %19 = "arith.constant"() {"value" = 1 : index} : () -> index
// CHECK-NEXT:     %20 = "arith.constant"() {"value" = 64 : index} : () -> index
// CHECK-NEXT:     %21 = "arith.constant"() {"value" = 64 : index} : () -> index
// CHECK-NEXT:     %22 = "arith.constant"() {"value" = 60 : index} : () -> index
// CHECK-NEXT:     "scf.parallel"(%18, %20, %19) ({
// CHECK-NEXT:     ^5(%23 : index):
// CHECK-NEXT:       "scf.for"(%18, %21, %19) ({
// CHECK-NEXT:       ^6(%24 : index):
// CHECK-NEXT:         "scf.for"(%18, %22, %19) ({
// CHECK-NEXT:         ^7(%25 : index):
// CHECK-NEXT:           %26 = "arith.constant"() {"value" = 1.0 : f32} : () -> f32
// CHECK-NEXT:           %27 = "arith.addf"(%14, %26) : (f32, f32) -> f32
// CHECK-NEXT:           "memref.store"(%27, %17, %23, %24, %25) : (f32, memref<64x64x60xf32, strided<[4900, 70, 1], offset: 19956>>, index, index, index) -> ()
// CHECK-NEXT:           "scf.yield"() : () -> ()
// CHECK-NEXT:         }) : (index, index, index) -> ()
// CHECK-NEXT:         "scf.yield"() : () -> ()
// CHECK-NEXT:       }) : (index, index, index) -> ()
// CHECK-NEXT:       "scf.yield"() : () -> ()
// CHECK-NEXT:     }) {"operand_segment_sizes" = array<i32: 1, 1, 1, 0>} : (index, index, index) -> ()
// CHECK-NEXT:     "func.return"() : () -> ()
// CHECK-NEXT:   }) {"function_type" = (f32, memref<?x?x?xf32>) -> (), "sym_name" = "stencil_float32_arg"} : () -> ()
// CHECK-NEXT: }) : () -> ()
