// RUN: xdsl-opt %s -p convert-stencil-to-ll-mlir --print-op-generic | filecheck %s

"builtin.module"() ({
    "func.func"() ({
    ^0(%0 : !stencil.field<?x?xf64>):
        %1 = "stencil.cast"(%0) {"lb" = #stencil.index<-4, -4>, "ub" = #stencil.index<68, 68>} : (!stencil.field<?x?xf64>) -> !stencil.field<72x72xf64>
        %2 = "stencil.load"(%1) {"lb" = #stencil.index<-4, -4>, "ub" = #stencil.index<68, 68>} : (!stencil.field<72x72xf64>) -> !stencil.temp<72x72xf64>
        "stencil.apply"(%2) ({
        ^b0(%3: !stencil.temp<72x72xf64>):
            %4 = "stencil.access"(%3) {"offset" = #stencil.index<-1, 0, 1>} : (!stencil.temp<72x72xf64>) -> f64
        }) {"lb" = #stencil.index<0, 0>, "ub" = #stencil.index<64, 68>} : (!stencil.temp<72x72xf64>) -> ()
        "func.return"() : () -> ()
    }) {"sym_name" = "test_funcop_lowering", "function_type" = (!stencil.field<?x?xf64>) -> (), "sym_visibility" = "private"} : () -> ()
}) : () -> ()

// CHECK:      "builtin.module"() ({
// CHECK-NEXT:   "func.func"() ({
// CHECK-NEXT:   ^0(%0 : memref<?x?xf64>):
// CHECK-NEXT:     %1 = "memref.cast"(%0) : (memref<?x?xf64>) -> memref<72x72xf64>
// CHECK-NEXT:     %2 = "memref.subview"(%1) {"static_offsets" = array<i64: 0, 0>, "static_sizes" = array<i64: 72, 72>, "static_strides" = array<i64: 1, 1>, "operand_segment_sizes" = array<i32: 1, 0, 0, 0>} : (memref<72x72xf64>) -> memref<72x72xf64, strided<[72, 1]>>
// CHECK-NEXT:     %3 = "arith.constant"() {"value" = 0 : index} : () -> index
// CHECK-NEXT:     %4 = "arith.constant"() {"value" = 1 : index} : () -> index
// CHECK-NEXT:     %5 = "arith.constant"() {"value" = 64 : index} : () -> index
// CHECK-NEXT:     %6 = "arith.constant"() {"value" = 68 : index} : () -> index
// CHECK-NEXT:     "scf.parallel"(%3, %5, %4) ({
// CHECK-NEXT:     ^1(%7 : index):
// CHECK-NEXT:       "scf.for"(%3, %6, %4) ({
// CHECK-NEXT:       ^2(%8 : index):
// CHECK-NEXT:         %9 = "arith.constant"() {"value" = 3 : index} : () -> index
// CHECK-NEXT:         %10 = "arith.constant"() {"value" = 4 : index} : () -> index
// CHECK-NEXT:         %11 = "arith.addi"(%7, %9) : (index, index) -> index
// CHECK-NEXT:         %12 = "arith.addi"(%8, %10) : (index, index) -> index
// CHECK-NEXT:         %13 = "memref.load"(%2, %11, %12) : (memref<72x72xf64, strided<[72, 1]>>, index, index) -> f64
// CHECK-NEXT:         "scf.yield"() : () -> ()
// CHECK-NEXT:       }) : (index, index, index) -> ()
// CHECK-NEXT:       "scf.yield"() : () -> ()
// CHECK-NEXT:     }) {"operand_segment_sizes" = array<i32: 1, 1, 1, 0>} : (index, index, index) -> ()
// CHECK-NEXT:     "func.return"() : () -> ()
// CHECK-NEXT:   }) {"sym_name" = "test_funcop_lowering", "function_type" = (memref<?x?xf64>) -> (), "sym_visibility" = "private"} : () -> ()
// CHECK-NEXT: }) : () -> ()
