import pytest

from xdsl.dialects.wasmssa import (
    AddOp,
    AndOp,
    CopySignOp,
    DivOp,
    DivSIOp,
    DivUIOp,
    EqOp,
    EqzOp,
    GeOp,
    GeSIOp,
    GeUIOp,
    GtOp,
    GtSIOp,
    GtUIOp,
    LeOp,
    LeSIOp,
    LeUIOp,
    LtOp,
    LtSIOp,
    LtUIOp,
    MaxOp,
    MinOp,
    MulOp,
    NeOp,
    OrOp,
    RemSIOp,
    RemUIOp,
    SubOp,
    XOrOp,
)
from xdsl.irdl import IRDLOperation
from xdsl.traits import Commutative, NoMemoryEffect, OpTrait, Pure


@pytest.mark.parametrize(
    "op_type, expected_traits",
    [
        (AddOp, [Pure(), Commutative()]),
        (AndOp, [Pure(), Commutative()]),
        (DivOp, [Pure()]),
        (DivUIOp, [NoMemoryEffect()]),
        (DivSIOp, [NoMemoryEffect()]),
        (MulOp, [Pure(), Commutative()]),
        (OrOp, [Pure(), Commutative()]),
        (SubOp, [Pure()]),
        (RemUIOp, [NoMemoryEffect()]),
        (RemSIOp, [NoMemoryEffect()]),
        (XOrOp, [Pure(), Commutative()]),
        (MinOp, [Pure(), Commutative()]),
        (MaxOp, [Pure(), Commutative()]),
        (CopySignOp, [Pure()]),
        (EqOp, [Pure(), Commutative()]),
        (NeOp, [Pure(), Commutative()]),
        (LtSIOp, [Pure()]),
        (LtUIOp, [Pure()]),
        (LeSIOp, [Pure()]),
        (LeUIOp, [Pure()]),
        (GtSIOp, [Pure()]),
        (GtUIOp, [Pure()]),
        (GeSIOp, [Pure()]),
        (GeUIOp, [Pure()]),
        (LtOp, [Pure()]),
        (LeOp, [Pure()]),
        (GtOp, [Pure()]),
        (GeOp, [Pure()]),
        (EqzOp, [Pure()]),
    ],
)
def test_traits(
    op_type: type[IRDLOperation],
    expected_traits: list[OpTrait],
):
    assert op_type.traits.traits == frozenset(expected_traits)
