"""
This type stub file was generated by pyright.
"""

DEFAULT_CLIPBOARD = ...

def wrapif(f):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    ...
@wrapif
def copy(*args, **kwargs):  # -> _NotImplementedType:
    ...
@wrapif
def paste(*args, **kwargs):  # -> str | bytes:
    ...
@wrapif
def clear(*args, **kwargs):  # -> _NotImplementedType:
    ...
