"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod

"""
Provides the abstract base class from which all clipboard implementations are derived.
"""

class ClipboardException(Exception): ...
class ClipboardSetupException(ClipboardException): ...

class ClipboardBase(ABC):
    """
    Abstract base class for Clipboard implementations.
    """
    @abstractmethod
    def copy(self, data: str | bytes, encoding: str = ...):  # -> _NotImplementedType:
        ...
    @abstractmethod
    def paste(self, encoding=..., text=..., errors=...) -> str | bytes: ...
    @abstractmethod
    def clear(self):  # -> _NotImplementedType:
        ...
