"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod

"""
This type stub file was generated by pyright.
"""

class ClipboardException(Exception): ...
class ClipboardSetupException(ClipboardException): ...

class ClipboardBase(ABC):
    """
    Abstract base class for Clipboard implementations.
    """
    @abstractmethod
    def copy(self, data: str | bytes, encoding: str = ...): ...
    @abstractmethod
    def paste(self, encoding=..., text=..., errors=...) -> str | bytes: ...
    @abstractmethod
    def clear(self): ...
