"""
This type stub file was generated by pyright.
"""

from functools import wraps

from .base import ClipboardBase

"""
This type stub file was generated by pyright.
"""
logger = ...

class _PBCopyPBPasteBackend(ClipboardBase):
    """
    MacOS Clipboard backend using pbcopy/pbpaste

    """
    def __init__(self) -> None: ...
    def copy(self, data: str | bytes, encoding: str = ...) -> None:
        """
        Copy data into the clipboard

        :param data: the data to be copied to the clipboard. Can be str or bytes.
        :param encoding: same meaning as in ``subprocess.Popen``.
        :return: None
        """
        ...

    def paste(self, encoding=..., text=..., errors=...) -> str | bytes:
        """
        Retrieve data from the clipboard

        :param encoding: same meaning as in ``subprocess.run``
        :param text: same meaning as in ``subprocess.run``
        :param errors: same meaning as in ``subprocess.run``
        :return: the clipboard contents. return type is binary by default.
        If any of ``encoding``, ``errors``, or ``text`` are specified, the result type is str
        """
        ...

    def clear(self):
        """
        Clear the clipboard contents

        :return:
        """
        ...

class _PasteboardBackend(ClipboardBase):
    """
    MacOS Clipboard backend using the ``pasteboard`` package.
    """
    def __init__(self) -> None: ...
    def copy(self, data: str | bytes, encoding: str = ...):
        """

        :param data: data to copy to the clipboard
        :param encoding: this parameter is ignored on this backend
        :return:
        """
        ...

    def paste(self, encoding: str = ..., text: bool = ..., errors: str = ...):
        """
        Retrieve contents of the clipboard

        :param encoding: same meaning as in ``bytes.encode``. Implies ``text=True``
        :param text: if True, bytes object will be en
        :param errors: same meaning as in ``bytes.encode``. Implies ``text=True``.
        :return: clipboard contents. Return value is bytes by default
        or str if any of ``encoding``, ``text``, or ``errors`` is provided.
        """
        ...

    def clear(self):
        """
        Clear the clipboard contents

        :return:
        """
        ...

class MacOSClip(ClipboardBase):
    """
    Provides Clipboard functionality for MacOS.

    Defers to one of two backends: :py:class:`_PasteboardBackend` (the default) or :py:class:`_PBCopyPBPasteBackend`.
    """
    def __init__(self, _backend=...) -> None: ...
    @wraps(_PasteboardBackend.copy)
    def copy(self, *args, **kwargs): ...
    @wraps(_PasteboardBackend.paste)
    def paste(self, *args, **kwargs): ...
    @wraps(_PasteboardBackend.clear)
    def clear(self): ...
