"""
This type stub file was generated by pyright.
"""

from .base import ClipboardBase

"""
This type stub file was generated by pyright.
"""

def detect_clipboard() -> ClipboardBase:
    """
    Determine what implementation to use based on ``sys.platform``
    """
    ...
