"""
This type stub file was generated by pyright.
"""

from .base import ClipboardBase

"""
Provides clipboard functionality for Windows via the ``pywin32`` package
"""
_TIMEOUT = ...
_CF_FORMATS = ...

class UnparsableClipboardFormatException(Exception): ...
class ClipboardNotTextFormatException(Exception): ...

class _Win32Clipboard:
    """
    Class for handling lower level details of managing Windows Clipboard
    """
    def __init__(self) -> None: ...
    def __enter__(self):  # -> Self:
        ...
    def __exit__(self, exc_type, exc_val, exc_tb):  # -> None:
        ...
    def open(self, *, _timeout=...):  # -> Self:
        ...
    def close(self):  # -> None:
        ...
    def __getattr__(self, item):  # -> Any:
        ...

class WindowsClipboard(ClipboardBase):
    def __init__(self) -> None: ...
    def copy(self, data: str | bytes, encoding=...):  # -> None:
        """Copy given string into system clipboard."""
        ...

    def clear(self) -> None:
        """
        Clear the clipboard contents

        :return:
        """
        ...

    def paste(
        self, encoding: str = ..., text: bool = ..., errors: str = ...
    ) -> str | bytes:
        """
        Returns clipboard contents

        :param encoding: same meaning as in ``bytes.encode``. Implies ``text=True``
        :param text: if True, bytes object will be en
        :param errors: same meaning as in ``bytes.encode``. Implies ``text=True``.
        :return: clipboard contents. Return value is bytes by default
            or str if any of ``encoding``, ``text``, or ``errors`` is provided.
        """
        ...
