"""
This type stub file was generated by pyright.
"""

from .base import ClipboardBase

"""
This type stub file was generated by pyright.
"""

class XclipClipboard(ClipboardBase):
    def __init__(self) -> None: ...
    def copy(self, data: str | bytes, encoding: str = ...) -> None:
        """
        Copy data into the clipboard

        :param data: the data to be copied to the clipboard. Can be str or bytes.
        :param encoding: same meaning as in ``subprocess.Popen``.
        :return: None
        """
        ...

    def paste(self, encoding: str = ..., text: bool = ..., errors: str = ...):
        """
        Retrieve data from the clipboard

        :param encoding: same meaning as in ``subprocess.run``
        :param text: same meaning as in ``subprocess.run``
        :param errors: same meaning as in ``subprocess.run``
        :return: the clipboard contents. return type is binary by default.
            If any of ``encoding``, ``errors``, or ``text`` are specified, the result type is str
        """
        ...

    def clear(self):
        """
        Clear the clipboard contents

        :return:
        """
        ...
