"""
This type stub file was generated by pyright.
"""

from llvmlite.binding import ffi

def create_context():  # -> ContextRef:
    ...
def get_global_context():  # -> GlobalContextRef:
    ...

class ContextRef(ffi.ObjectRef):
    def __init__(self, context_ptr) -> None: ...

class GlobalContextRef(ContextRef): ...
