LLVMContextRef = ...
LLVMModuleRef = ...
LLVMValueRef = ...
LLVMTypeRef = ...
LLVMExecutionEngineRef = ...
LLVMPassManagerBuilderRef = ...
LLVMPassManagerRef = ...
LLVMTargetDataRef = ...
LLVMTargetLibraryInfoRef = ...
LLVMTargetRef = ...
LLVMTargetMachineRef = ...
LLVMMemoryBufferRef = ...
LLVMAttributeListIterator = ...
LLVMElementIterator = ...
LLVMAttributeSetIterator = ...
LLVMGlobalsIterator = ...
LLVMFunctionsIterator = ...
LLVMBlocksIterator = ...
LLVMArgumentsIterator = ...
LLVMInstructionsIterator = ...
LLVMOperandsIterator = ...
LLVMIncomingBlocksIterator = ...
LLVMTypesIterator = ...
LLVMObjectCacheRef = ...
LLVMObjectFileRef = ...
LLVMSectionIteratorRef = ...
LLVMOrcLLJITRef = ...
LLVMOrcDylibTrackerRef = ...
LLVMTimePassesHandlerRef = ...
LLVMPipelineTuningOptionsRef = ...
LLVMModulePassManagerRef = ...
LLVMFunctionPassManagerRef = ...
LLVMPassBuilderRef = ...

class _LLVMLock:
    def __init__(self) -> None: ...
    def register(self, acq_fn, rel_fn): ...
    def unregister(self, acq_fn, rel_fn): ...
    def __enter__(self): ...
    def __exit__(self, *exc_details): ...

class _suppress_cleanup_errors:
    def __init__(self, context) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_value, traceback): ...

class _lib_wrapper:
    __slots__ = ...
    def __init__(self) -> None: ...
    def __getattr__(self, name): ...

class _lib_fn_wrapper:
    __slots__ = ...
    def __init__(self, lock, cfn) -> None: ...
    @property
    def argtypes(self): ...
    @argtypes.setter
    def argtypes(self, argtypes): ...
    @property
    def restype(self): ...
    @restype.setter
    def restype(self, restype): ...
    def __call__(self, *args, **kwargs): ...

_importlib_resources_path = ...
lib = ...

def register_lock_callback(acq_fn, rel_fn): ...
def unregister_lock_callback(acq_fn, rel_fn): ...

class _DeadPointer: ...

class OutputString:
    _as_parameter_ = ...
    @classmethod
    def from_return(cls, ptr): ...
    def __init__(self, owned=..., init=...) -> None: ...
    def close(self): ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
    def __del__(self, _is_shutting_down=...): ...
    def __bool__(self): ...

    __nonzero__ = ...
    @property
    def bytes(self): ...

def ret_string(ptr): ...
def ret_bytes(ptr): ...

class ObjectRef:
    _closed = ...
    _as_parameter_ = ...
    _owned = ...
    def __init__(self, ptr) -> None: ...
    def close(self): ...
    def detach(self): ...
    @property
    def closed(self): ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
    def __del__(self, _is_shutting_down=...): ...
    def __bool__(self): ...
    def __eq__(self, other) -> bool: ...

    __nonzero__ = ...
    def __hash__(self) -> int: ...
