"""
This type stub file was generated by pyright.
"""

def initialize():
    """
    Initialize the LLVM core (deprecated).

    This function is deprecated and will raise an error when called.
    LLVM initialization is now handled automatically and no longer
    requires explicit initialization calls.

    Raises:
        RuntimeError: Always raised as this function is no longer needed.
    """
    ...

def initialize_all_targets():  # -> None:
    """
    Initialize all targets. Necessary before targets can be looked up
    via the :class:`Target` class.
    """
    ...

def initialize_all_asmprinters():  # -> None:
    """
    Initialize all code generators. Necessary before generating
    any assembly or machine code via the :meth:`TargetMachine.emit_object`
    and :meth:`TargetMachine.emit_assembly` methods.
    """
    ...

def initialize_native_target():  # -> None:
    """
    Initialize the native (host) target.  Necessary before doing any
    code generation.
    """
    ...

def initialize_native_asmprinter():  # -> None:
    """
    Initialize the native ASM printer.
    """
    ...

def initialize_native_asmparser():  # -> None:
    """
    Initialize the native ASM parser.
    """
    ...

def shutdown():  # -> None:
    ...

llvm_version_info = ...
