def initialize(): ...
def initialize_all_targets(): ...
def initialize_all_asmprinters(): ...
def initialize_native_target(): ...
def initialize_native_asmprinter(): ...
def initialize_native_asmparser(): ...
def shutdown(): ...

llvm_version_info = ...
