#!/usr/bin/env python3

import argparse
from xdsl.xdsl_opt_main import xDSLOptMain
from xdsl.dialects.onnx.dialect import Onnx
from xdsl.dialects.stencil.stencil import Stencil
# passes
from xdsl.passes.arith_expansion import arith_expansion_pass
from xdsl.passes.onnx_opt import onnx_opt_pass


class OptMain(xDSLOptMain):

    def register_all_dialects(self):
        super().register_all_dialects()
        onnx = Onnx(self.ctx)
        stencil = Stencil(self.ctx)

    def register_all_passes(self):
        super().register_all_passes()
        self.available_passes["arith-expand"] = arith_expansion_pass
        self.available_passes["onnx-opt"] = onnx_opt_pass

    def register_all_arguments(self, arg_parser: argparse.ArgumentParser):
        super().register_all_arguments(arg_parser)


def __main__():
    xdsl_main = OptMain()
    xdsl_main.run()


if __name__ == "__main__":
    __main__()
