// RUN: true

// The pdl_interp code at the bottom of the file was generated by
// running `xdsl-opt -p convert-pdl-to-pdl-interp{optimize_for_eqsat=true}`
// on the following pdl patterns.
// These patterns stem from egg's math test cases.

//pdl.pattern @comm_add : benefit(1) {
//  %0 = pdl.type : f32
//  %b = pdl.operand : %0
//  %a = pdl.operand : %0
//  %1 = pdl.operation "arith.addf" (%a, %b : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %2 = pdl.result 0 of %1
//  pdl.rewrite %1 {
//    %3 = pdl.operation "arith.addf" (%b, %a : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %4 = pdl.result 0 of %3
//    pdl.replace %1 with (%4 : !pdl.value)
//  }
//}
//pdl.pattern @comm_mul : benefit(1) {
//  %0 = pdl.type : f32
//  %b = pdl.operand : %0
//  %a = pdl.operand : %0
//  %1 = pdl.operation "arith.mulf" (%a, %b : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %2 = pdl.result 0 of %1
//  pdl.rewrite %1 {
//    %3 = pdl.operation "arith.mulf" (%b, %a : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %4 = pdl.result 0 of %3
//    pdl.replace %1 with (%4 : !pdl.value)
//  }
//}
//pdl.pattern @assoc_add : benefit(1) {
//  %0 = pdl.type : f32
//  %c = pdl.operand : %0
//  %b = pdl.operand : %0
//  %a = pdl.operand : %0
//  %1 = pdl.operation "arith.addf" (%b, %c : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %2 = pdl.result 0 of %1
//  %3 = pdl.operation "arith.addf" (%a, %2 : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %4 = pdl.result 0 of %3
//  pdl.rewrite %3 {
//    %5 = pdl.operation "arith.addf" (%a, %b : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %6 = pdl.result 0 of %5
//    %7 = pdl.operation "arith.addf" (%6, %c : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %8 = pdl.result 0 of %7
//    pdl.replace %3 with (%8 : !pdl.value)
//  }
//}
//pdl.pattern @assoc_mul : benefit(1) {
//  %0 = pdl.type : f32
//  %c = pdl.operand : %0
//  %b = pdl.operand : %0
//  %a = pdl.operand : %0
//  %1 = pdl.operation "arith.mulf" (%b, %c : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %2 = pdl.result 0 of %1
//  %3 = pdl.operation "arith.mulf" (%a, %2 : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %4 = pdl.result 0 of %3
//  pdl.rewrite %3 {
//    %5 = pdl.operation "arith.mulf" (%a, %b : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %6 = pdl.result 0 of %5
//    %7 = pdl.operation "arith.mulf" (%6, %c : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %8 = pdl.result 0 of %7
//    pdl.replace %3 with (%8 : !pdl.value)
//  }
//}
//pdl.pattern @sub_canon : benefit(1) {
//  %0 = pdl.type : f32
//  %b = pdl.operand : %0
//  %a = pdl.operand : %0
//  %1 = pdl.operation "arith.subf" (%a, %b : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %2 = pdl.result 0 of %1
//  pdl.rewrite %1 {
//    %3 = pdl.attribute = -1.000000e+00 : f32
//    %4 = pdl.operation "arith.constant" {"value" = %3} -> (%0 : !pdl.type)
//    %5 = pdl.result 0 of %4
//    %6 = pdl.operation "arith.mulf" (%5, %b : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %7 = pdl.result 0 of %6
//    %8 = pdl.operation "arith.addf" (%a, %7 : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %9 = pdl.result 0 of %8
//    pdl.replace %1 with (%9 : !pdl.value)
//  }
//}
//pdl.pattern @zero_add : benefit(1) {
//  %0 = pdl.type : f32
//  %a = pdl.operand : %0
//  %1 = pdl.attribute = 0.000000e+00 : f32
//  %2 = pdl.operation "arith.constant" {"value" = %1} -> (%0 : !pdl.type)
//  %3 = pdl.result 0 of %2
//  %4 = pdl.operation "arith.addf" (%a, %3 : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %5 = pdl.result 0 of %4
//  pdl.rewrite %4 {
//    pdl.replace %4 with (%a : !pdl.value)
//  }
//}
//pdl.pattern @zero_mul : benefit(1) {
//  %0 = pdl.type : f32
//  %a = pdl.operand : %0
//  %1 = pdl.attribute = 0.000000e+00 : f32
//  %2 = pdl.operation "arith.constant" {"value" = %1} -> (%0 : !pdl.type)
//  %3 = pdl.result 0 of %2
//  %4 = pdl.operation "arith.mulf" (%a, %3 : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %5 = pdl.result 0 of %4
//  pdl.rewrite %4 {
//    %6 = pdl.attribute = 0.000000e+00 : f32
//    %7 = pdl.operation "arith.constant" {"value" = %6} -> (%0 : !pdl.type)
//    %8 = pdl.result 0 of %7
//    pdl.replace %4 with (%8 : !pdl.value)
//  }
//}
//pdl.pattern @one_mul : benefit(1) {
//  %0 = pdl.type : f32
//  %a = pdl.operand : %0
//  %1 = pdl.attribute = 1.000000e+00 : f32
//  %2 = pdl.operation "arith.constant" {"value" = %1} -> (%0 : !pdl.type)
//  %3 = pdl.result 0 of %2
//  %4 = pdl.operation "arith.mulf" (%a, %3 : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %5 = pdl.result 0 of %4
//  pdl.rewrite %4 {
//    pdl.replace %4 with (%a : !pdl.value)
//  }
//}
//pdl.pattern @cancel_sub : benefit(1) {
//  %0 = pdl.type : f32
//  %a = pdl.operand : %0
//  %1 = pdl.operation "arith.subf" (%a, %a : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %2 = pdl.result 0 of %1
//  pdl.rewrite %1 {
//    %3 = pdl.attribute = 0.000000e+00 : f32
//    %4 = pdl.operation "arith.constant" {"value" = %3} -> (%0 : !pdl.type)
//    %5 = pdl.result 0 of %4
//    pdl.replace %1 with (%5 : !pdl.value)
//  }
//}
//pdl.pattern @distribute : benefit(1) {
//  %0 = pdl.type : f32
//  %c = pdl.operand : %0
//  %b = pdl.operand : %0
//  %a = pdl.operand : %0
//  %1 = pdl.operation "arith.addf" (%b, %c : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %2 = pdl.result 0 of %1
//  %3 = pdl.operation "arith.mulf" (%a, %2 : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %4 = pdl.result 0 of %3
//  pdl.rewrite %3 {
//    %5 = pdl.operation "arith.mulf" (%a, %b : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %6 = pdl.result 0 of %5
//    %7 = pdl.operation "arith.mulf" (%a, %c : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %8 = pdl.result 0 of %7
//    %9 = pdl.operation "arith.addf" (%6, %8 : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %10 = pdl.result 0 of %9
//    pdl.replace %3 with (%10 : !pdl.value)
//  }
//}
//pdl.pattern @factor : benefit(1) {
//  %0 = pdl.type : f32
//  %c = pdl.operand : %0
//  %a = pdl.operand : %0
//  %b = pdl.operand : %0
//  %1 = pdl.operation "arith.mulf" (%a, %b : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %2 = pdl.result 0 of %1
//  %3 = pdl.operation "arith.mulf" (%a, %c : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %4 = pdl.result 0 of %3
//  %5 = pdl.operation "arith.addf" (%2, %4 : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %6 = pdl.result 0 of %5
//  pdl.rewrite %5 {
//    %7 = pdl.operation "arith.addf" (%b, %c : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %8 = pdl.result 0 of %7
//    %9 = pdl.operation "arith.mulf" (%a, %8 : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %10 = pdl.result 0 of %9
//    pdl.replace %5 with (%10 : !pdl.value)
//  }
//}
//pdl.pattern @pow_mul : benefit(1) {
//  %0 = pdl.type : f32
//  %c = pdl.operand : %0
//  %a = pdl.operand : %0
//  %b = pdl.operand : %0
//  %1 = pdl.operation "math.powf" (%a, %b : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %2 = pdl.result 0 of %1
//  %3 = pdl.operation "math.powf" (%a, %c : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %4 = pdl.result 0 of %3
//  %5 = pdl.operation "arith.mulf" (%2, %4 : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %6 = pdl.result 0 of %5
//  pdl.rewrite %5 {
//    %7 = pdl.operation "arith.addf" (%b, %c : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %8 = pdl.result 0 of %7
//    %9 = pdl.operation "math.powf" (%a, %8 : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %10 = pdl.result 0 of %9
//    pdl.replace %5 with (%10 : !pdl.value)
//  }
//}
//pdl.pattern @pow1 : benefit(1) {
//  %0 = pdl.type : f32
//  %x = pdl.operand : %0
//  %1 = pdl.attribute = 1.000000e+00 : f32
//  %2 = pdl.operation "arith.constant" {"value" = %1} -> (%0 : !pdl.type)
//  %3 = pdl.result 0 of %2
//  %4 = pdl.operation "math.powf" (%x, %3 : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %5 = pdl.result 0 of %4
//  pdl.rewrite %4 {
//    pdl.replace %4 with (%x : !pdl.value)
//  }
//}
//pdl.pattern @pow2 : benefit(1) {
//  %0 = pdl.type : f32
//  %x = pdl.operand : %0
//  %1 = pdl.attribute = 2.000000e+00 : f32
//  %2 = pdl.operation "arith.constant" {"value" = %1} -> (%0 : !pdl.type)
//  %3 = pdl.result 0 of %2
//  %4 = pdl.operation "math.powf" (%x, %3 : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//  %5 = pdl.result 0 of %4
//  pdl.rewrite %4 {
//    %6 = pdl.operation "arith.mulf" (%x, %x : !pdl.value, !pdl.value) -> (%0 : !pdl.type)
//    %7 = pdl.result 0 of %6
//    pdl.replace %4 with (%7 : !pdl.value)
//  }
//}


builtin.module {
  pdl_interp.func @matcher(%0 : !pdl.operation) {
    %1 = pdl_interp.get_result 0 of %0
    pdl_interp.is_not_null %1 : !pdl.value -> ^bb0, ^bb1
  ^bb0:
    %2 = ematch.get_class_result %1
    pdl_interp.is_not_null %2 : !pdl.value -> ^bb2, ^bb1
  ^bb1:
    pdl_interp.finalize
  ^bb2:
    pdl_interp.switch_operation_name of %0 to ["arith.addf", "arith.mulf", "arith.subf", "math.powf"](^bb3, ^bb4, ^bb5, ^bb6) -> ^bb1
  ^bb3:
    pdl_interp.check_operand_count of %0 is 2 -> ^bb7, ^bb1
  ^bb7:
    pdl_interp.check_result_count of %0 is 1 -> ^bb8, ^bb1
  ^bb8:
    %3 = pdl_interp.get_operand 0 of %0
    pdl_interp.is_not_null %3 : !pdl.value -> ^bb9, ^bb1
  ^bb9:
    %4 = pdl_interp.get_operand 1 of %0
    pdl_interp.is_not_null %4 : !pdl.value -> ^bb10, ^bb1
  ^bb10:
    %5 = pdl_interp.get_value_type of %3 : !pdl.type
    %6 = pdl_interp.get_value_type of %2 : !pdl.type
    pdl_interp.are_equal %5, %6 : !pdl.type -> ^bb11, ^bb12
  ^bb12:
    %7 = ematch.get_class_vals %4
    pdl_interp.foreach %8 : !pdl.value in %7 {
      %9 = pdl_interp.get_defining_op of %8 : !pdl.value {position = "root.operand[1].defining_op"}
      pdl_interp.is_not_null %9 : !pdl.operation -> ^bb13, ^bb14
    ^bb14:
      pdl_interp.continue
    ^bb13:
      pdl_interp.check_operation_name of %9 is "arith.mulf" -> ^bb15, ^bb14
    ^bb15:
      pdl_interp.check_operand_count of %9 is 2 -> ^bb16, ^bb14
    ^bb16:
      pdl_interp.check_result_count of %9 is 1 -> ^bb17, ^bb14
    ^bb17:
      %10 = pdl_interp.get_result 0 of %9
      pdl_interp.is_not_null %10 : !pdl.value -> ^bb18, ^bb14
    ^bb18:
      %11 = ematch.get_class_result %10
      pdl_interp.is_not_null %11 : !pdl.value -> ^bb19, ^bb14
    ^bb19:
      pdl_interp.are_equal %11, %4 : !pdl.value -> ^bb20, ^bb14
    ^bb20:
      %12 = pdl_interp.get_operand 1 of %9
      pdl_interp.is_not_null %12 : !pdl.value -> ^bb21, ^bb14
    ^bb21:
      %13 = ematch.get_class_vals %3
      pdl_interp.foreach %14 : !pdl.value in %13 {
        %15 = pdl_interp.get_defining_op of %14 : !pdl.value {position = "root.operand[0].defining_op"}
        pdl_interp.is_not_null %15 : !pdl.operation -> ^bb22, ^bb23
      ^bb23:
        pdl_interp.continue
      ^bb22:
        pdl_interp.check_operation_name of %15 is "arith.mulf" -> ^bb24, ^bb23
      ^bb24:
        pdl_interp.check_operand_count of %15 is 2 -> ^bb25, ^bb23
      ^bb25:
        pdl_interp.check_result_count of %15 is 1 -> ^bb26, ^bb23
      ^bb26:
        %16 = pdl_interp.get_operand 0 of %15
        pdl_interp.is_not_null %16 : !pdl.value -> ^bb27, ^bb23
      ^bb27:
        %17 = pdl_interp.get_operand 1 of %15
        pdl_interp.is_not_null %17 : !pdl.value -> ^bb28, ^bb23
      ^bb28:
        %18 = pdl_interp.get_operand 0 of %9
        pdl_interp.are_equal %16, %18 : !pdl.value -> ^bb29, ^bb23
      ^bb29:
        %19 = pdl_interp.get_result 0 of %15
        pdl_interp.is_not_null %19 : !pdl.value -> ^bb30, ^bb23
      ^bb30:
        %20 = ematch.get_class_result %19
        pdl_interp.is_not_null %20 : !pdl.value -> ^bb31, ^bb23
      ^bb31:
        pdl_interp.are_equal %20, %3 : !pdl.value -> ^bb32, ^bb23
      ^bb32:
        %21 = pdl_interp.get_value_type of %16 : !pdl.type
        %22 = pdl_interp.get_value_type of %17 : !pdl.type
        pdl_interp.are_equal %21, %22 : !pdl.type -> ^bb33, ^bb23
      ^bb33:
        %23 = pdl_interp.get_value_type of %20 : !pdl.type
        pdl_interp.are_equal %21, %23 : !pdl.type -> ^bb34, ^bb23
      ^bb34:
        %24 = pdl_interp.get_value_type of %12 : !pdl.type
        pdl_interp.are_equal %21, %24 : !pdl.type -> ^bb35, ^bb23
      ^bb35:
        %25 = pdl_interp.get_value_type of %11 : !pdl.type
        pdl_interp.are_equal %21, %25 : !pdl.type -> ^bb36, ^bb23
      ^bb36:
        %26 = pdl_interp.get_value_type of %2 : !pdl.type
        pdl_interp.are_equal %21, %26 : !pdl.type -> ^bb37, ^bb23
      ^bb37:
        pdl_interp.check_type %21 is f32 -> ^bb38, ^bb23
      ^bb38:
        %27 = ematch.get_class_representative %17
        %28 = ematch.get_class_representative %12
        %29 = ematch.get_class_representative %16
        pdl_interp.record_match @rewriters::@factor(%27, %28, %29, %0 : !pdl.value, !pdl.value, !pdl.value, !pdl.operation) : benefit(1), loc([]), root("arith.addf") -> ^bb23
      } -> ^bb14
    } -> ^bb1
  ^bb11:
    pdl_interp.check_type %5 is f32 -> ^bb39, ^bb12
  ^bb39:
    %30 = pdl_interp.get_value_type of %4 : !pdl.type
    pdl_interp.are_equal %5, %30 : !pdl.type -> ^bb40, ^bb41
  ^bb41:
    %31 = ematch.get_class_vals %4
    pdl_interp.foreach %32 : !pdl.value in %31 {
      %33 = pdl_interp.get_defining_op of %32 : !pdl.value {position = "root.operand[1].defining_op"}
      pdl_interp.is_not_null %33 : !pdl.operation -> ^bb42, ^bb43
    ^bb43:
      pdl_interp.continue
    ^bb42:
      pdl_interp.switch_operation_name of %33 to ["arith.addf", "arith.constant"](^bb44, ^bb45) -> ^bb43
    ^bb44:
      pdl_interp.check_operand_count of %33 is 2 -> ^bb46, ^bb43
    ^bb46:
      pdl_interp.check_result_count of %33 is 1 -> ^bb47, ^bb43
    ^bb47:
      %34 = pdl_interp.get_result 0 of %33
      pdl_interp.is_not_null %34 : !pdl.value -> ^bb48, ^bb43
    ^bb48:
      %35 = ematch.get_class_result %34
      pdl_interp.is_not_null %35 : !pdl.value -> ^bb49, ^bb43
    ^bb49:
      pdl_interp.are_equal %35, %4 : !pdl.value -> ^bb50, ^bb43
    ^bb50:
      %36 = pdl_interp.get_value_type of %35 : !pdl.type
      pdl_interp.are_equal %36, %5 : !pdl.type -> ^bb51, ^bb43
    ^bb51:
      %37 = pdl_interp.get_operand 1 of %33
      pdl_interp.is_not_null %37 : !pdl.value -> ^bb52, ^bb43
    ^bb52:
      %38 = pdl_interp.get_operand 0 of %33
      pdl_interp.is_not_null %38 : !pdl.value -> ^bb53, ^bb43
    ^bb53:
      %39 = pdl_interp.get_value_type of %38 : !pdl.type
      pdl_interp.are_equal %39, %5 : !pdl.type -> ^bb54, ^bb43
    ^bb54:
      %40 = pdl_interp.get_value_type of %37 : !pdl.type
      pdl_interp.are_equal %40, %5 : !pdl.type -> ^bb55, ^bb43
    ^bb55:
      %41 = ematch.get_class_representative %3
      %42 = ematch.get_class_representative %38
      %43 = ematch.get_class_representative %37
      pdl_interp.record_match @rewriters::@assoc_add(%41, %42, %43, %0 : !pdl.value, !pdl.value, !pdl.value, !pdl.operation) : benefit(1), loc([]), root("arith.addf") -> ^bb43
    ^bb45:
      pdl_interp.check_operand_count of %33 is 0 -> ^bb56, ^bb43
    ^bb56:
      pdl_interp.check_result_count of %33 is 1 -> ^bb57, ^bb43
    ^bb57:
      %44 = pdl_interp.get_result 0 of %33
      pdl_interp.is_not_null %44 : !pdl.value -> ^bb58, ^bb43
    ^bb58:
      %45 = ematch.get_class_result %44
      pdl_interp.is_not_null %45 : !pdl.value -> ^bb59, ^bb43
    ^bb59:
      pdl_interp.are_equal %45, %4 : !pdl.value -> ^bb60, ^bb43
    ^bb60:
      %46 = pdl_interp.get_value_type of %45 : !pdl.type
      pdl_interp.are_equal %46, %5 : !pdl.type -> ^bb61, ^bb43
    ^bb61:
      %47 = pdl_interp.get_attribute "value" of %33
      pdl_interp.is_not_null %47 : !pdl.attribute -> ^bb62, ^bb43
    ^bb62:
      pdl_interp.check_attribute %47 is 0.000000e+00 : f32 -> ^bb63, ^bb43
    ^bb63:
      %48 = ematch.get_class_representative %3
      pdl_interp.record_match @rewriters::@zero_add(%48, %0 : !pdl.value, !pdl.operation) : benefit(1), loc([]), root("arith.addf") -> ^bb43
    } -> ^bb12
  ^bb40:
    %49 = ematch.get_class_representative %4
    %50 = ematch.get_class_representative %3
    pdl_interp.record_match @rewriters::@comm_add(%49, %50, %0 : !pdl.value, !pdl.value, !pdl.operation) : benefit(1), loc([]), root("arith.addf") -> ^bb41
  ^bb4:
    pdl_interp.check_operand_count of %0 is 2 -> ^bb64, ^bb1
  ^bb64:
    pdl_interp.check_result_count of %0 is 1 -> ^bb65, ^bb1
  ^bb65:
    %51 = pdl_interp.get_operand 0 of %0
    pdl_interp.is_not_null %51 : !pdl.value -> ^bb66, ^bb1
  ^bb66:
    %52 = pdl_interp.get_operand 1 of %0
    pdl_interp.is_not_null %52 : !pdl.value -> ^bb67, ^bb1
  ^bb67:
    %53 = pdl_interp.get_value_type of %51 : !pdl.type
    %54 = pdl_interp.get_value_type of %2 : !pdl.type
    pdl_interp.are_equal %53, %54 : !pdl.type -> ^bb68, ^bb69
  ^bb69:
    %55 = ematch.get_class_vals %52
    pdl_interp.foreach %56 : !pdl.value in %55 {
      %57 = pdl_interp.get_defining_op of %56 : !pdl.value {position = "root.operand[1].defining_op"}
      pdl_interp.is_not_null %57 : !pdl.operation -> ^bb70, ^bb71
    ^bb71:
      pdl_interp.continue
    ^bb70:
      pdl_interp.check_operation_name of %57 is "math.powf" -> ^bb72, ^bb71
    ^bb72:
      pdl_interp.check_operand_count of %57 is 2 -> ^bb73, ^bb71
    ^bb73:
      pdl_interp.check_result_count of %57 is 1 -> ^bb74, ^bb71
    ^bb74:
      %58 = pdl_interp.get_result 0 of %57
      pdl_interp.is_not_null %58 : !pdl.value -> ^bb75, ^bb71
    ^bb75:
      %59 = ematch.get_class_result %58
      pdl_interp.is_not_null %59 : !pdl.value -> ^bb76, ^bb71
    ^bb76:
      pdl_interp.are_equal %59, %52 : !pdl.value -> ^bb77, ^bb71
    ^bb77:
      %60 = pdl_interp.get_operand 1 of %57
      pdl_interp.is_not_null %60 : !pdl.value -> ^bb78, ^bb71
    ^bb78:
      %61 = ematch.get_class_vals %51
      pdl_interp.foreach %62 : !pdl.value in %61 {
        %63 = pdl_interp.get_defining_op of %62 : !pdl.value {position = "root.operand[0].defining_op"}
        pdl_interp.is_not_null %63 : !pdl.operation -> ^bb79, ^bb80
      ^bb80:
        pdl_interp.continue
      ^bb79:
        pdl_interp.check_operation_name of %63 is "math.powf" -> ^bb81, ^bb80
      ^bb81:
        pdl_interp.check_operand_count of %63 is 2 -> ^bb82, ^bb80
      ^bb82:
        pdl_interp.check_result_count of %63 is 1 -> ^bb83, ^bb80
      ^bb83:
        %64 = pdl_interp.get_operand 0 of %63
        pdl_interp.is_not_null %64 : !pdl.value -> ^bb84, ^bb80
      ^bb84:
        %65 = pdl_interp.get_operand 1 of %63
        pdl_interp.is_not_null %65 : !pdl.value -> ^bb85, ^bb80
      ^bb85:
        %66 = pdl_interp.get_operand 0 of %57
        pdl_interp.are_equal %64, %66 : !pdl.value -> ^bb86, ^bb80
      ^bb86:
        %67 = pdl_interp.get_result 0 of %63
        pdl_interp.is_not_null %67 : !pdl.value -> ^bb87, ^bb80
      ^bb87:
        %68 = ematch.get_class_result %67
        pdl_interp.is_not_null %68 : !pdl.value -> ^bb88, ^bb80
      ^bb88:
        pdl_interp.are_equal %68, %51 : !pdl.value -> ^bb89, ^bb80
      ^bb89:
        %69 = pdl_interp.get_value_type of %64 : !pdl.type
        %70 = pdl_interp.get_value_type of %65 : !pdl.type
        pdl_interp.are_equal %69, %70 : !pdl.type -> ^bb90, ^bb80
      ^bb90:
        %71 = pdl_interp.get_value_type of %68 : !pdl.type
        pdl_interp.are_equal %69, %71 : !pdl.type -> ^bb91, ^bb80
      ^bb91:
        %72 = pdl_interp.get_value_type of %60 : !pdl.type
        pdl_interp.are_equal %69, %72 : !pdl.type -> ^bb92, ^bb80
      ^bb92:
        %73 = pdl_interp.get_value_type of %59 : !pdl.type
        pdl_interp.are_equal %69, %73 : !pdl.type -> ^bb93, ^bb80
      ^bb93:
        %74 = pdl_interp.get_value_type of %2 : !pdl.type
        pdl_interp.are_equal %69, %74 : !pdl.type -> ^bb94, ^bb80
      ^bb94:
        pdl_interp.check_type %69 is f32 -> ^bb95, ^bb80
      ^bb95:
        %75 = ematch.get_class_representative %65
        %76 = ematch.get_class_representative %60
        %77 = ematch.get_class_representative %64
        pdl_interp.record_match @rewriters::@pow_mul(%75, %76, %77, %0 : !pdl.value, !pdl.value, !pdl.value, !pdl.operation) : benefit(1), loc([]), root("arith.mulf") -> ^bb80
      } -> ^bb71
    } -> ^bb1
  ^bb68:
    pdl_interp.check_type %53 is f32 -> ^bb96, ^bb69
  ^bb96:
    %78 = pdl_interp.get_value_type of %52 : !pdl.type
    pdl_interp.are_equal %53, %78 : !pdl.type -> ^bb97, ^bb98
  ^bb98:
    %79 = ematch.get_class_vals %52
    pdl_interp.foreach %80 : !pdl.value in %79 {
      %81 = pdl_interp.get_defining_op of %80 : !pdl.value {position = "root.operand[1].defining_op"}
      pdl_interp.is_not_null %81 : !pdl.operation -> ^bb99, ^bb100
    ^bb100:
      pdl_interp.continue
    ^bb99:
      pdl_interp.switch_operation_name of %81 to ["arith.mulf", "arith.constant", "arith.addf"](^bb101, ^bb102, ^bb103) -> ^bb100
    ^bb101:
      pdl_interp.check_operand_count of %81 is 2 -> ^bb104, ^bb100
    ^bb104:
      pdl_interp.check_result_count of %81 is 1 -> ^bb105, ^bb100
    ^bb105:
      %82 = pdl_interp.get_result 0 of %81
      pdl_interp.is_not_null %82 : !pdl.value -> ^bb106, ^bb100
    ^bb106:
      %83 = ematch.get_class_result %82
      pdl_interp.is_not_null %83 : !pdl.value -> ^bb107, ^bb100
    ^bb107:
      pdl_interp.are_equal %83, %52 : !pdl.value -> ^bb108, ^bb100
    ^bb108:
      %84 = pdl_interp.get_value_type of %83 : !pdl.type
      pdl_interp.are_equal %84, %53 : !pdl.type -> ^bb109, ^bb100
    ^bb109:
      %85 = pdl_interp.get_operand 1 of %81
      pdl_interp.is_not_null %85 : !pdl.value -> ^bb110, ^bb100
    ^bb110:
      %86 = pdl_interp.get_operand 0 of %81
      pdl_interp.is_not_null %86 : !pdl.value -> ^bb111, ^bb100
    ^bb111:
      %87 = pdl_interp.get_value_type of %86 : !pdl.type
      pdl_interp.are_equal %87, %53 : !pdl.type -> ^bb112, ^bb100
    ^bb112:
      %88 = pdl_interp.get_value_type of %85 : !pdl.type
      pdl_interp.are_equal %88, %53 : !pdl.type -> ^bb113, ^bb100
    ^bb113:
      %89 = ematch.get_class_representative %51
      %90 = ematch.get_class_representative %86
      %91 = ematch.get_class_representative %85
      pdl_interp.record_match @rewriters::@assoc_mul(%89, %90, %91, %0 : !pdl.value, !pdl.value, !pdl.value, !pdl.operation) : benefit(1), loc([]), root("arith.mulf") -> ^bb100
    ^bb102:
      pdl_interp.check_operand_count of %81 is 0 -> ^bb114, ^bb100
    ^bb114:
      pdl_interp.check_result_count of %81 is 1 -> ^bb115, ^bb100
    ^bb115:
      %92 = pdl_interp.get_result 0 of %81
      pdl_interp.is_not_null %92 : !pdl.value -> ^bb116, ^bb100
    ^bb116:
      %93 = ematch.get_class_result %92
      pdl_interp.is_not_null %93 : !pdl.value -> ^bb117, ^bb100
    ^bb117:
      pdl_interp.are_equal %93, %52 : !pdl.value -> ^bb118, ^bb100
    ^bb118:
      %94 = pdl_interp.get_value_type of %93 : !pdl.type
      pdl_interp.are_equal %94, %53 : !pdl.type -> ^bb119, ^bb100
    ^bb119:
      %95 = pdl_interp.get_attribute "value" of %81
      pdl_interp.is_not_null %95 : !pdl.attribute -> ^bb120, ^bb100
    ^bb120:
      pdl_interp.switch_attribute %95 to [0.000000e+00 : f32, 1.000000e+00 : f32](^bb121, ^bb122) -> ^bb100
    ^bb121:
      pdl_interp.record_match @rewriters::@zero_mul(%0 : !pdl.operation) : benefit(1), loc([]), root("arith.mulf") -> ^bb100
    ^bb122:
      %96 = ematch.get_class_representative %51
      pdl_interp.record_match @rewriters::@one_mul(%96, %0 : !pdl.value, !pdl.operation) : benefit(1), loc([]), root("arith.mulf") -> ^bb100
    ^bb103:
      pdl_interp.check_operand_count of %81 is 2 -> ^bb123, ^bb100
    ^bb123:
      pdl_interp.check_result_count of %81 is 1 -> ^bb124, ^bb100
    ^bb124:
      %97 = pdl_interp.get_result 0 of %81
      pdl_interp.is_not_null %97 : !pdl.value -> ^bb125, ^bb100
    ^bb125:
      %98 = ematch.get_class_result %97
      pdl_interp.is_not_null %98 : !pdl.value -> ^bb126, ^bb100
    ^bb126:
      pdl_interp.are_equal %98, %52 : !pdl.value -> ^bb127, ^bb100
    ^bb127:
      %99 = pdl_interp.get_value_type of %98 : !pdl.type
      pdl_interp.are_equal %99, %53 : !pdl.type -> ^bb128, ^bb100
    ^bb128:
      %100 = pdl_interp.get_operand 1 of %81
      pdl_interp.is_not_null %100 : !pdl.value -> ^bb129, ^bb100
    ^bb129:
      %101 = pdl_interp.get_operand 0 of %81
      pdl_interp.is_not_null %101 : !pdl.value -> ^bb130, ^bb100
    ^bb130:
      %102 = pdl_interp.get_value_type of %101 : !pdl.type
      pdl_interp.are_equal %102, %53 : !pdl.type -> ^bb131, ^bb100
    ^bb131:
      %103 = pdl_interp.get_value_type of %100 : !pdl.type
      pdl_interp.are_equal %103, %53 : !pdl.type -> ^bb132, ^bb100
    ^bb132:
      %104 = ematch.get_class_representative %51
      %105 = ematch.get_class_representative %101
      %106 = ematch.get_class_representative %100
      pdl_interp.record_match @rewriters::@distribute(%104, %105, %106, %0 : !pdl.value, !pdl.value, !pdl.value, !pdl.operation) : benefit(1), loc([]), root("arith.mulf") -> ^bb100
    } -> ^bb69
  ^bb97:
    %107 = ematch.get_class_representative %52
    %108 = ematch.get_class_representative %51
    pdl_interp.record_match @rewriters::@comm_mul(%107, %108, %0 : !pdl.value, !pdl.value, !pdl.operation) : benefit(1), loc([]), root("arith.mulf") -> ^bb98
  ^bb5:
    pdl_interp.check_operand_count of %0 is 2 -> ^bb133, ^bb1
  ^bb133:
    pdl_interp.check_result_count of %0 is 1 -> ^bb134, ^bb1
  ^bb134:
    %109 = pdl_interp.get_operand 0 of %0
    pdl_interp.is_not_null %109 : !pdl.value -> ^bb135, ^bb1
  ^bb135:
    %110 = pdl_interp.get_operand 1 of %0
    pdl_interp.is_not_null %110 : !pdl.value -> ^bb136, ^bb137
  ^bb137:
    %111 = pdl_interp.get_value_type of %109 : !pdl.type
    %112 = pdl_interp.get_value_type of %2 : !pdl.type
    pdl_interp.are_equal %111, %112 : !pdl.type -> ^bb138, ^bb1
  ^bb138:
    pdl_interp.check_type %111 is f32 -> ^bb139, ^bb1
  ^bb139:
    %113 = pdl_interp.get_operand 1 of %0
    pdl_interp.are_equal %109, %113 : !pdl.value -> ^bb140, ^bb1
  ^bb140:
    pdl_interp.record_match @rewriters::@cancel_sub(%0 : !pdl.operation) : benefit(1), loc([]), root("arith.subf") -> ^bb1
  ^bb136:
    %114 = pdl_interp.get_value_type of %109 : !pdl.type
    %115 = pdl_interp.get_value_type of %2 : !pdl.type
    pdl_interp.are_equal %114, %115 : !pdl.type -> ^bb141, ^bb137
  ^bb141:
    pdl_interp.check_type %114 is f32 -> ^bb142, ^bb137
  ^bb142:
    %116 = pdl_interp.get_value_type of %110 : !pdl.type
    pdl_interp.are_equal %114, %116 : !pdl.type -> ^bb143, ^bb137
  ^bb143:
    %117 = ematch.get_class_representative %110
    %118 = ematch.get_class_representative %109
    pdl_interp.record_match @rewriters::@sub_canon(%117, %118, %0 : !pdl.value, !pdl.value, !pdl.operation) : benefit(1), loc([]), root("arith.subf") -> ^bb137
  ^bb6:
    pdl_interp.check_operand_count of %0 is 2 -> ^bb144, ^bb1
  ^bb144:
    pdl_interp.check_result_count of %0 is 1 -> ^bb145, ^bb1
  ^bb145:
    %119 = pdl_interp.get_operand 0 of %0
    pdl_interp.is_not_null %119 : !pdl.value -> ^bb146, ^bb1
  ^bb146:
    %120 = pdl_interp.get_operand 1 of %0
    pdl_interp.is_not_null %120 : !pdl.value -> ^bb147, ^bb1
  ^bb147:
    %121 = pdl_interp.get_value_type of %119 : !pdl.type
    %122 = pdl_interp.get_value_type of %2 : !pdl.type
    pdl_interp.are_equal %121, %122 : !pdl.type -> ^bb148, ^bb1
  ^bb148:
    pdl_interp.check_type %121 is f32 -> ^bb149, ^bb1
  ^bb149:
    %123 = ematch.get_class_vals %120
    pdl_interp.foreach %124 : !pdl.value in %123 {
      %125 = pdl_interp.get_defining_op of %124 : !pdl.value {position = "root.operand[1].defining_op"}
      pdl_interp.is_not_null %125 : !pdl.operation -> ^bb150, ^bb151
    ^bb151:
      pdl_interp.continue
    ^bb150:
      pdl_interp.check_operation_name of %125 is "arith.constant" -> ^bb152, ^bb151
    ^bb152:
      pdl_interp.check_operand_count of %125 is 0 -> ^bb153, ^bb151
    ^bb153:
      pdl_interp.check_result_count of %125 is 1 -> ^bb154, ^bb151
    ^bb154:
      %126 = pdl_interp.get_result 0 of %125
      pdl_interp.is_not_null %126 : !pdl.value -> ^bb155, ^bb151
    ^bb155:
      %127 = ematch.get_class_result %126
      pdl_interp.is_not_null %127 : !pdl.value -> ^bb156, ^bb151
    ^bb156:
      pdl_interp.are_equal %127, %120 : !pdl.value -> ^bb157, ^bb151
    ^bb157:
      %128 = pdl_interp.get_value_type of %127 : !pdl.type
      pdl_interp.are_equal %128, %121 : !pdl.type -> ^bb158, ^bb151
    ^bb158:
      %129 = pdl_interp.get_attribute "value" of %125
      pdl_interp.is_not_null %129 : !pdl.attribute -> ^bb159, ^bb151
    ^bb159:
      pdl_interp.switch_attribute %129 to [1.000000e+00 : f32, 2.000000e+00 : f32](^bb160, ^bb161) -> ^bb151
    ^bb160:
      %130 = ematch.get_class_representative %119
      pdl_interp.record_match @rewriters::@pow1(%130, %0 : !pdl.value, !pdl.operation) : benefit(1), loc([]), root("math.powf") -> ^bb151
    ^bb161:
      %131 = ematch.get_class_representative %119
      pdl_interp.record_match @rewriters::@pow2(%131, %0 : !pdl.value, !pdl.operation) : benefit(1), loc([]), root("math.powf") -> ^bb151
    } -> ^bb1
  }
  builtin.module @rewriters {
    pdl_interp.func @factor(%0 : !pdl.value, %1 : !pdl.value, %2 : !pdl.value, %3 : !pdl.operation) {
      %4 = ematch.get_class_result %0
      %5 = ematch.get_class_result %1
      %6 = pdl_interp.create_type f32
      %7 = pdl_interp.create_operation "arith.addf"(%4, %5 : !pdl.value, !pdl.value) -> (%6 : !pdl.type)
      %8 = ematch.dedup %7
      %9 = pdl_interp.get_result 0 of %8
      %10 = ematch.get_class_result %9
      %11 = ematch.get_class_result %2
      %12 = pdl_interp.create_operation "arith.mulf"(%11, %10 : !pdl.value, !pdl.value) -> (%6 : !pdl.type)
      %13 = ematch.dedup %12
      %14 = pdl_interp.get_result 0 of %13
      %15 = ematch.get_class_result %14
      %16 = pdl_interp.create_range %15 : !pdl.value
      ematch.union %3 : !pdl.operation, %16 : !pdl.range<value>
      pdl_interp.finalize
    }
    pdl_interp.func @assoc_add(%0 : !pdl.value, %1 : !pdl.value, %2 : !pdl.value, %3 : !pdl.operation) {
      %4 = ematch.get_class_result %0
      %5 = ematch.get_class_result %1
      %6 = pdl_interp.create_type f32
      %7 = pdl_interp.create_operation "arith.addf"(%4, %5 : !pdl.value, !pdl.value) -> (%6 : !pdl.type)
      %8 = ematch.dedup %7
      %9 = pdl_interp.get_result 0 of %8
      %10 = ematch.get_class_result %9
      %11 = ematch.get_class_result %2
      %12 = pdl_interp.create_operation "arith.addf"(%10, %11 : !pdl.value, !pdl.value) -> (%6 : !pdl.type)
      %13 = ematch.dedup %12
      %14 = pdl_interp.get_result 0 of %13
      %15 = ematch.get_class_result %14
      %16 = pdl_interp.create_range %15 : !pdl.value
      ematch.union %3 : !pdl.operation, %16 : !pdl.range<value>
      pdl_interp.finalize
    }
    pdl_interp.func @zero_add(%0 : !pdl.value, %1 : !pdl.operation) {
      %2 = ematch.get_class_result %0
      %3 = pdl_interp.create_range %2 : !pdl.value
      ematch.union %1 : !pdl.operation, %3 : !pdl.range<value>
      pdl_interp.finalize
    }
    pdl_interp.func @comm_add(%0 : !pdl.value, %1 : !pdl.value, %2 : !pdl.operation) {
      %3 = ematch.get_class_result %0
      %4 = ematch.get_class_result %1
      %5 = pdl_interp.create_type f32
      %6 = pdl_interp.create_operation "arith.addf"(%3, %4 : !pdl.value, !pdl.value) -> (%5 : !pdl.type)
      %7 = ematch.dedup %6
      %8 = pdl_interp.get_result 0 of %7
      %9 = ematch.get_class_result %8
      %10 = pdl_interp.create_range %9 : !pdl.value
      ematch.union %2 : !pdl.operation, %10 : !pdl.range<value>
      pdl_interp.finalize
    }
    pdl_interp.func @pow_mul(%0 : !pdl.value, %1 : !pdl.value, %2 : !pdl.value, %3 : !pdl.operation) {
      %4 = ematch.get_class_result %0
      %5 = ematch.get_class_result %1
      %6 = pdl_interp.create_type f32
      %7 = pdl_interp.create_operation "arith.addf"(%4, %5 : !pdl.value, !pdl.value) -> (%6 : !pdl.type)
      %8 = ematch.dedup %7
      %9 = pdl_interp.get_result 0 of %8
      %10 = ematch.get_class_result %9
      %11 = ematch.get_class_result %2
      %12 = pdl_interp.create_operation "math.powf"(%11, %10 : !pdl.value, !pdl.value) -> (%6 : !pdl.type)
      %13 = ematch.dedup %12
      %14 = pdl_interp.get_result 0 of %13
      %15 = ematch.get_class_result %14
      %16 = pdl_interp.create_range %15 : !pdl.value
      ematch.union %3 : !pdl.operation, %16 : !pdl.range<value>
      pdl_interp.finalize
    }
    pdl_interp.func @assoc_mul(%0 : !pdl.value, %1 : !pdl.value, %2 : !pdl.value, %3 : !pdl.operation) {
      %4 = ematch.get_class_result %0
      %5 = ematch.get_class_result %1
      %6 = pdl_interp.create_type f32
      %7 = pdl_interp.create_operation "arith.mulf"(%4, %5 : !pdl.value, !pdl.value) -> (%6 : !pdl.type)
      %8 = ematch.dedup %7
      %9 = pdl_interp.get_result 0 of %8
      %10 = ematch.get_class_result %9
      %11 = ematch.get_class_result %2
      %12 = pdl_interp.create_operation "arith.mulf"(%10, %11 : !pdl.value, !pdl.value) -> (%6 : !pdl.type)
      %13 = ematch.dedup %12
      %14 = pdl_interp.get_result 0 of %13
      %15 = ematch.get_class_result %14
      %16 = pdl_interp.create_range %15 : !pdl.value
      ematch.union %3 : !pdl.operation, %16 : !pdl.range<value>
      pdl_interp.finalize
    }
    pdl_interp.func @zero_mul(%0 : !pdl.operation) {
      %1 = pdl_interp.create_attribute 0.000000e+00 : f32
      %2 = pdl_interp.create_type f32
      %3 = pdl_interp.create_operation "arith.constant" {"value" = %1} -> (%2 : !pdl.type)
      %4 = ematch.dedup %3
      %5 = pdl_interp.get_result 0 of %4
      %6 = ematch.get_class_result %5
      %7 = pdl_interp.create_range %6 : !pdl.value
      ematch.union %0 : !pdl.operation, %7 : !pdl.range<value>
      pdl_interp.finalize
    }
    pdl_interp.func @one_mul(%0 : !pdl.value, %1 : !pdl.operation) {
      %2 = ematch.get_class_result %0
      %3 = pdl_interp.create_range %2 : !pdl.value
      ematch.union %1 : !pdl.operation, %3 : !pdl.range<value>
      pdl_interp.finalize
    }
    pdl_interp.func @distribute(%0 : !pdl.value, %1 : !pdl.value, %2 : !pdl.value, %3 : !pdl.operation) {
      %4 = ematch.get_class_result %0
      %5 = ematch.get_class_result %1
      %6 = pdl_interp.create_type f32
      %7 = pdl_interp.create_operation "arith.mulf"(%4, %5 : !pdl.value, !pdl.value) -> (%6 : !pdl.type)
      %8 = ematch.dedup %7
      %9 = pdl_interp.get_result 0 of %8
      %10 = ematch.get_class_result %9
      %11 = ematch.get_class_result %2
      %12 = pdl_interp.create_operation "arith.mulf"(%4, %11 : !pdl.value, !pdl.value) -> (%6 : !pdl.type)
      %13 = ematch.dedup %12
      %14 = pdl_interp.get_result 0 of %13
      %15 = ematch.get_class_result %14
      %16 = pdl_interp.create_operation "arith.addf"(%10, %15 : !pdl.value, !pdl.value) -> (%6 : !pdl.type)
      %17 = ematch.dedup %16
      %18 = pdl_interp.get_result 0 of %17
      %19 = ematch.get_class_result %18
      %20 = pdl_interp.create_range %19 : !pdl.value
      ematch.union %3 : !pdl.operation, %20 : !pdl.range<value>
      pdl_interp.finalize
    }
    pdl_interp.func @comm_mul(%0 : !pdl.value, %1 : !pdl.value, %2 : !pdl.operation) {
      %3 = ematch.get_class_result %0
      %4 = ematch.get_class_result %1
      %5 = pdl_interp.create_type f32
      %6 = pdl_interp.create_operation "arith.mulf"(%3, %4 : !pdl.value, !pdl.value) -> (%5 : !pdl.type)
      %7 = ematch.dedup %6
      %8 = pdl_interp.get_result 0 of %7
      %9 = ematch.get_class_result %8
      %10 = pdl_interp.create_range %9 : !pdl.value
      ematch.union %2 : !pdl.operation, %10 : !pdl.range<value>
      pdl_interp.finalize
    }
    pdl_interp.func @cancel_sub(%0 : !pdl.operation) {
      %1 = pdl_interp.create_attribute 0.000000e+00 : f32
      %2 = pdl_interp.create_type f32
      %3 = pdl_interp.create_operation "arith.constant" {"value" = %1} -> (%2 : !pdl.type)
      %4 = ematch.dedup %3
      %5 = pdl_interp.get_result 0 of %4
      %6 = ematch.get_class_result %5
      %7 = pdl_interp.create_range %6 : !pdl.value
      ematch.union %0 : !pdl.operation, %7 : !pdl.range<value>
      pdl_interp.finalize
    }
    pdl_interp.func @sub_canon(%0 : !pdl.value, %1 : !pdl.value, %2 : !pdl.operation) {
      %3 = pdl_interp.create_attribute -1.000000e+00 : f32
      %4 = pdl_interp.create_type f32
      %5 = pdl_interp.create_operation "arith.constant" {"value" = %3} -> (%4 : !pdl.type)
      %6 = ematch.dedup %5
      %7 = pdl_interp.get_result 0 of %6
      %8 = ematch.get_class_result %7
      %9 = ematch.get_class_result %0
      %10 = pdl_interp.create_operation "arith.mulf"(%8, %9 : !pdl.value, !pdl.value) -> (%4 : !pdl.type)
      %11 = ematch.dedup %10
      %12 = pdl_interp.get_result 0 of %11
      %13 = ematch.get_class_result %12
      %14 = ematch.get_class_result %1
      %15 = pdl_interp.create_operation "arith.addf"(%14, %13 : !pdl.value, !pdl.value) -> (%4 : !pdl.type)
      %16 = ematch.dedup %15
      %17 = pdl_interp.get_result 0 of %16
      %18 = ematch.get_class_result %17
      %19 = pdl_interp.create_range %18 : !pdl.value
      ematch.union %2 : !pdl.operation, %19 : !pdl.range<value>
      pdl_interp.finalize
    }
    pdl_interp.func @pow1(%0 : !pdl.value, %1 : !pdl.operation) {
      %2 = ematch.get_class_result %0
      %3 = pdl_interp.create_range %2 : !pdl.value
      ematch.union %1 : !pdl.operation, %3 : !pdl.range<value>
      pdl_interp.finalize
    }
    pdl_interp.func @pow2(%0 : !pdl.value, %1 : !pdl.operation) {
      %2 = ematch.get_class_result %0
      %3 = pdl_interp.create_type f32
      %4 = pdl_interp.create_operation "arith.mulf"(%2, %2 : !pdl.value, !pdl.value) -> (%3 : !pdl.type)
      %5 = ematch.dedup %4
      %6 = pdl_interp.get_result 0 of %5
      %7 = ematch.get_class_result %6
      %8 = pdl_interp.create_range %7 : !pdl.value
      ematch.union %1 : !pdl.operation, %8 : !pdl.range<value>
      pdl_interp.finalize
    }
  }
}
