import dis
from types import FunctionType

from bytecode import Bytecode, Instr

from xdsl.dialects.builtin import ModuleOp, StringAttr
from xdsl.dialects.pybc import (
    BinaryOpOp,
    CoOp,
    LoadConstOp,
    LoadFastOp,
    PybcOp,
    ResumeOp,
    ReturnValueOp,
    StoreFastOp,
)
from xdsl.ir import Operation
from xdsl.irdl import IRDLOperation

_BINARY_OP_MAP: dict[str, PybcOp] = {
    "+": PybcOp.OP_ADD,
    "-": PybcOp.OP_SUB,
    "*": PybcOp.OP_MUL,
    "/": PybcOp.OP_DIV,
}


class PybcGen:
    def __init__(self) -> None:
        pass

    def inst_to_pybc_op(self, inst: dis.Instruction) -> IRDLOperation:
        match inst.opname:
            case "RESUME":
                return ResumeOp()

            case "LOAD_FAST":
                assert inst.arg is not None
                return LoadFastOp(inst.arg)

            case "LOAD_CONST":
                return LoadConstOp(inst.argval)

            case "STORE_FAST":
                assert inst.arg is not None
                return StoreFastOp(inst.arg)

            case "BINARY_OP":
                symbol = inst.argrepr
                if symbol not in _BINARY_OP_MAP:
                    raise NotImplementedError(f"Unknown binary operator: {symbol!r}")
                return BinaryOpOp(_BINARY_OP_MAP[symbol])

            case "RETURN_VALUE":
                return ReturnValueOp()

            case other:
                raise NotImplementedError(f"Instruction not supported: {other}")

    def pybcop_to_inst(
        self, op: Operation, co_varname: list[StringAttr]
    ) -> Instr | None:
        match op:
            case LoadFastOp():
                return Instr("LOAD_FAST", co_varname[op.var_index.value.data].data)

            case StoreFastOp():
                return Instr("STORE_FAST", co_varname[op.var_index.value.data].data)

            case LoadConstOp():
                return Instr("LOAD_CONST", op.const.value.data)

            case BinaryOpOp():
                return Instr("BINARY_OP", op.op.data.value)

            case ResumeOp():
                return Instr("RESUME", 0)

            case ReturnValueOp():
                return Instr("RETURN_VALUE")

            case other:
                raise NotImplementedError(f"Instruction {other} not supported")

    def gen_pybytecode(self, func) -> ModuleOp:
        ops: list[Operation] = []
        for inst in dis.get_instructions(func):
            ops.append(self.inst_to_pybc_op(inst))

        co_op = CoOp(
            func.__name__,
            list(func.__code__.co_varnames),
            arg_count=func.__code__.co_argcount,
            ops=ops,
        )

        return ModuleOp([co_op])

    def gen_bytecode(self, module: ModuleOp) -> FunctionType | None:
        block = module.body.first_block
        if not block:
            return None

        co_op = block.first_op
        if not co_op:
            return None

        co_varname = list(co_op.var_names)
        func_name = co_op.sym_name.data
        arg_names = [s.data for s in co_varname[: co_op.arg_count.value.data]]

        insts: list[Instr] = []
        for op in co_op.walk():
            if isinstance(op, CoOp):
                continue

            inst = self.pybcop_to_inst(op, co_varname)
            if inst:
                insts.append(inst)

        bc = Bytecode(insts)
        bc.argnames = arg_names
        bc.argcount = len(arg_names)
        bc.name = func_name

        code = bc.to_code()
        return FunctionType(code, globals(), func_name)


class PybcJIT:
    @classmethod
    def disas(cls, func):
        def wrapper(*args, **kwargs):

            print("Bytecode: ")
            dis.dis(func)
            generator = PybcGen()
            module = generator.gen_pybytecode(func)
            rebuild = generator.gen_bytecode(module)

            print("Module: ")
            print(module)

            print("Regenerated bytecode: ")
            dis.dis(rebuild)

            result = func(*args, **kwargs)
            rebuilt_result = rebuild(*args, **kwargs)

            print(f"Result:\nExpect: {result}\nGot: {rebuilt_result}")
            return result

        return wrapper


@PybcJIT.disas
def func(a: float, b: float) -> float:
    return a + b


func(2, 3)
