import dis
from types import FunctionType

from bytecode import Bytecode, Instr

from xdsl.builder import Builder
from xdsl.dialects.builtin import ModuleOp
from xdsl.dialects.pybc import (
    BinaryOpOp,
    FunctionOp,
    LoadConstOp,
    LoadFastOp,
    PybcOp,
    # ResumeOp,
    ReturnValueOp,
    StoreFastOp,
)
from xdsl.ir import Operation, SSAValue
from xdsl.irdl import IRDLOperation
from xdsl.rewriter import InsertPoint

_BINARY_OP_MAP: dict[str, PybcOp] = {
    "+": PybcOp.OP_ADD,
    "-": PybcOp.OP_SUB,
    "*": PybcOp.OP_MUL,
    "/": PybcOp.OP_DIV,
}


def ssavalue_name(ssa: SSAValue):
    return ssa.name_hint


class PybcGen:
    def __init__(self) -> None:
        self.stack: list[IRDLOperation] = []
        self.str_ssa_mapping: dict[str, SSAValue] = dict()

    def inst_to_pybc_op(self, inst: dis.Instruction) -> IRDLOperation | None:
        match inst.opname:
            case "RESUME":
                return None

            case "LOAD_FAST":
                assert inst.arg is not None

                self.stack.append(
                    LoadFastOp(inst.arg, self.str_ssa_mapping[inst.argval])
                )
                return self.stack[-1]

            case "LOAD_CONST":
                self.stack.append(LoadConstOp(inst.argval))
                return self.stack[-1]

            case "STORE_FAST":
                assert inst.arg is not None
                self.stack.pop()
                return StoreFastOp(inst.arg, self.str_ssa_mapping[inst.argval])

            case "BINARY_OP":
                symbol = inst.argrepr
                if symbol not in _BINARY_OP_MAP:
                    raise NotImplementedError(f"Unknown binary operator: {symbol!r}")

                lhs = self.stack.pop()
                rhs = self.stack.pop()
                self.stack.append(BinaryOpOp(_BINARY_OP_MAP[symbol], lhs, rhs))

                return self.stack[-1]

            case "RETURN_VALUE":
                return ReturnValueOp(self.stack.pop())

            case other:
                raise NotImplementedError(f"Instruction not supported: {other}")

    def pybcop_to_inst(self, op: Operation) -> Instr | None:
        match op:
            case LoadFastOp():
                return Instr("LOAD_FAST", op.var_name.name_hint)

            case StoreFastOp():
                return Instr("STORE_FAST", op.var_name.name_hint)

            case LoadConstOp():
                return Instr("LOAD_CONST", op.const.value.data)

            case BinaryOpOp():
                return Instr("BINARY_OP", op.op.data.value)

            case ReturnValueOp():
                return Instr("RETURN_VALUE")

            case other:
                raise NotImplementedError(f"Instruction {other} not supported")

    def gen_pybytecode(self, func: FunctionType) -> ModuleOp:
        name = func.__name__
        code = func.__code__

        arg_count = code.co_argcount + code.co_kwonlyargcount

        sym_list = code.co_varnames
        arg_list = sym_list[:arg_count]
        var_list = sym_list[arg_count:]

        funcop = FunctionOp(
            name,
            arg_list,
            var_list,
            ops=[],
        )
        builder = Builder(insertion_point=InsertPoint.at_start(funcop.body.first_block))
        assert funcop.body.first_block is not None
        for i, arg in enumerate(funcop.body.first_block.args):
            self.str_ssa_mapping[arg_list[i]] = arg

        for inst in dis.get_instructions(func):
            op = self.inst_to_pybc_op(inst)
            if op:
                builder.insert(op)

        self.stack = []
        self.str_ssa_mapping = dict()

        return ModuleOp([funcop])

    def gen_bytecode(self, module: ModuleOp) -> FunctionType | None:
        block = module.body.first_block
        if not block:
            return None

        func_op = block.first_op
        if not func_op:
            return None

        arg_names = [arg.name_hint for arg in func_op.body.first_block.args]

        insts: list[Instr] = [Instr("RESUME", 0)]
        for op in func_op.walk():
            if isinstance(op, FunctionOp):
                continue

            inst = self.pybcop_to_inst(op)
            if inst:
                insts.append(inst)

        bc = Bytecode(insts)
        bc.argnames = arg_names
        bc.argcount = len(arg_names)
        bc.name = func_op.sym_name.data.removeprefix('"').removesuffix('"')

        code = bc.to_code()
        new_func = FunctionType(code, globals(), name=bc.name)
        return new_func


class PybcJIT:
    @classmethod
    def disas(cls, func):
        def wrapper(*args, **kwargs):

            print("Bytecode: ")
            dis.dis(func)
            generator = PybcGen()
            module = generator.gen_pybytecode(func)

            print("Module: ")
            print(module)

            rebuild = generator.gen_bytecode(module)
            print(rebuild, func)
            assert rebuild is not None
            print("Regenerated bytecode: ")
            dis.dis(rebuild)

            result = func(*args, **kwargs)
            rebuilt_result = rebuild(*args, **kwargs)

            print(f"Result:\nExpect: {result}\nGot: {rebuilt_result}")
            return result

        return wrapper


@PybcJIT.disas
def func(a: float, b: float) -> float:
    return a + b


func(2, 3)
