nav:
  - xDSL: "https://xdsl.dev/"
  - Getting Started: index.md
  - Tutorial Notebooks: marimo
  - API Reference: reference
  - User Guide: guides
  - News: "https://xdsl.dev/news/"
  - Events: "https://xdsl.dev/events/2025-HiPEAC/"
  - About: "https://xdsl.dev/about/challenge/"
