
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = ["lzstring2"]
name = "marimo_docs"
version = "0.1.0"

[tool.hatch.build.targets.wheel]
include = ["blocks.py"]

[tool.uv.sources]
lzstring2 = { git = "https://github.com/superlopuh/lz-string.git" }
