"""
This type stub file was generated by pyright.
"""

def discover_tests(startdir):  # -> TestSuite:
    """Discover test under a directory"""
    ...

def run_tests(suite=..., xmloutput=..., verbosity=...):  # -> TestResult:
    """
    args
    ----
    - suite [TestSuite]
        A suite of all tests to run
    - xmloutput [str or None]
        Path of XML output directory (optional)
    - verbosity [int]
        Verbosity level of tests output

    Returns the TestResult object after running the test *suite*.
    """
    ...

def main(): ...
