# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: black formatting

on:
   # Trigger the workflow on push or pull request,
   # but only for the master branch
   push:
     branches:
       - main
   pull_request:
     branches:
       - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install formatting requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-optional.txt
    - name: Check format with black 
      run: |
        # Returns en error code if the files are not formatted
        black --diff --color --check .
