# This workflow will install MLIR, Python dependencies, run tests and lint with a single version of Python

name: CI - Codecov

on:
  # Trigger the workflow after ci-mlir completes
  workflow_run:
    workflows: [CI - Python-based Testing]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
      with:
        path: xdsl

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.10'
      uses: Wandalen/wretry.action@v1
      with:
        action: codecov/codecov-action@v4
        attempt_delay: 10000
        attempt_limit: 10
        with: |
          fail_ci_if_error: true
          verbose: true
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
