ARG MLIR_VERSION

FROM ubuntu:22.04 as build

ARG MLIR_VERSION

# Install dependencies
RUN apt update \
 && apt install --yes --no-install-recommends git cmake build-essential ca-certificates ninja-build clang lld python3.10-dev pip
RUN mkdir llvm-project \
 && cd llvm-project \
 && git init \
 && git remote add origin https://github.com/llvm/llvm-project.git \
 && git fetch --depth 1 origin ${MLIR_VERSION} \
 && git checkout FETCH_HEAD
RUN mkdir llvm-project/build \
 && cd llvm-project/build \
 && cmake -G Ninja ../llvm \
      -DLLVM_ENABLE_PROJECTS=mlir \
      -DLLVM_TARGETS_TO_BUILD="X86" \
      -DLLVM_ENABLE_LLD=ON \
      -DCMAKE_C_COMPILER=clang \
      -DCMAKE_CXX_COMPILER=clang++ \
      -DCMAKE_BUILD_TYPE=Release \
      -DLLVM_ENABLE_ASSERTIONS=ON \
      -DCMAKE_INSTALL_PREFIX=install
RUN cd llvm-project/build \
 && cmake --build . --target install

FROM ubuntu:22.04 as install
RUN --mount=from=build,target=install,source=llvm-project/build/install,rw \
    cp -R install/* /usr/local
RUN apt update \
 && apt install --no-install-recommends --yes openssl
