name: Update Lockfile Bot

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'dependabot/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install 3.12

      - name: Update lockfile
        run: |
          echo "\`\`\`" > uv_output.md
          XDSL_VERSION_OVERRIDE="0+dynamic" make venv &>> uv_output.md
          echo "\`\`\`" >> uv_output.md
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add uv.lock
          git commit -m "Update uv lockfile" -F uv_output.md || echo "No changes to commit"
          git push
