name: Update Lockfile Bot

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  lock:
    if: |
      ${{ github.event.issue.pull_request }} &&
      contains(github.event.comment.body, 'please update lockfile') &&
      contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install the package locally and update lockfile
        run: |
          # Install all default extras.
          XDSL_VERSION_OVERRIDE="0+dynamic" make venv

      - uses: EndBug/add-and-commit@v9
        with:
          add: uv.lock
